name: build

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  release-x64:
    runs-on: windows-2025-vs2026
    steps:
      - uses: actions/checkout@v6
      - uses: microsoft/setup-msbuild@v3
        with:
          msbuild-architecture: x64
      - run: msbuild Entries.sln /m /t:Build /p:Configuration=Release /p:Platform=x64
      - run: .\x64\Release\Entries.exe --help
